### ISSUE TITLE
Alchemy bug

### ISSUE THREAD

**Issue by iobiarg** [Rumaruka/Thaumic-Bases-Unofficial#7]
hi there, been using and testing and having some issues with certain alchemy stuff: i can create crystals in the crucible for every aspect but not for pannus iter and fames (so far) the essence just stay in the crucible until it starts to go into the air, i can take all the other aspect with the crystals (lets see, from leather, i can take out bestia and stuff) but pannus stays in the crucible. Same with iter and fames... any clue what could be going on?I'm using tc6 beta24 pluss tc addons: your mod, thaumic additions, thaumic pheripery and rustic+ thaumaturgy in case you know any of this could cause the bug.

**Comment by Rumaruka** [comment]
Maybe this bugs with vanila TC, but i see, if i want solutions - i update addon
Also I will ask for more details (gif, small video, etc.) for the full picture
Sorry that I did not answer earlier!

**Comment by wamc2017** [comment]
The issue was brought up before on TCs bugtracker: https://github.com/Azanor/thaumcraft-beta/issues/1425

You're registering the aspects to late for Thaumcraft to catch them up, so you've either to move the registering to preinit or register the crucible recipes yourself.
If you're on it, you should also consider using the [AspectRegistryEvent](https://github.com/Azanor/thaumcraft-api/blob/6e1ecde4b1c0a627cf937bc41e6abfae2644fca8/aspects/AspectRegistryEvent.java) which was added in beta 20, to avoid future incompatibilities...

**Comment by Rumaruka** [comment]
> If you're on it, you should also consider using the [AspectRegistryEvent](https://github.com/Azanor/thaumcraft-api/blob/6e1ecde4b1c0a627cf937bc41e6abfae2644fca8/aspects/AspectRegistryEvent.java) which was added in beta 20, to avoid future incompatibilities...

OOOpps Im looking - thanks =)

**Comment by Rumaruka** [comment]
Stop
Can I find out about version my addon @iobiarg ?

**Comment by wamc2017** [comment]
It's reproduceable with thaumicbases-3.2.255.2r-ForTC6B21, the latest version from curseforge...

The issue is solved, if you move this line to preinit:
https://github.com/Rumaruka/Thaumic-Bases-Unofficial/blob/258b646de48c99b5e7c2ccfd0fb1de732e2e1473/java/com/rumaruka/tb/core/TBCore.java#L117

But you're still using the old deprecated way to add/remove aspects here (why you should use the new AspectRegistryEvent instead...):
https://github.com/Rumaruka/Thaumic-Bases-Unofficial/blob/258b646de48c99b5e7c2ccfd0fb1de732e2e1473/java/com/rumaruka/tb/init/TBThaumonomicon.java#L447-L488

**Comment by iobiarg** [comment]
thaumicbases-3.2.255.2r-ForTC6B21 was the file i was using, the last one in curse on your mod page. good luck

**Comment by Rumaruka** [comment]
Fix
Now You make crystals :3

**Comment by iobiarg** [comment]
will wait for the file update, since it hasn't yet showed in curse... probably in a couple of hours if you uploaded it when answered this. thanks

**Comment by Rumaruka** [comment]
I don't update in curse , because will fix more bugs. Just wait

**Comment by Rumaruka** [comment]
Fix in new version
Close #7

**Comment by dredhorse** [comment]
HI, I still have an issue with 3.2.270.4r that ModTweaker can't find Iter.

**Comment by Rumaruka** [comment]
> HI, I still have an issue with 3.2.270.4r that ModTweaker can't find Iter.

Use ThaumicJei (Iter in Ender Pearl)

**Comment by Rumaruka** [comment]
And I don`t make ModTweaker Support

**Comment by dredhorse** [comment]
well, I would like to add Iter to a custom recipe I have, but I can't use Iter as Thaumic Bases don't register the aspects correctly as it seems?

correct me if I'm wrong and I move this to ModTweaker.

**Comment by dredhorse** [comment]
the code in question: https://bitbucket.org/dredhorse/offthebeatenpath/src/master/scripts/artisan_carpenter_worktable.zs
I would have liked to add Iter to the boats, I removed that atm with a workaround.
